#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

PLUGIN_ROOT_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

export PLUGIN_COMMAND_PREFIX="discourse"
export PLUGIN_ROOT_PATH
export STORAGE_ROOT="${DOKKU_LIB_ROOT}/data/storage"
export DISCOURSE_DOCKER_IMAGE_ROOT="$STORAGE_ROOT/discourse_docker"
export CONTAINER_NAME="standalone"
export DISCOURSE_IMAGE_NAME="local_discourse/$CONTAINER_NAME"
export DISCOURSE_APPS="$DOKKU_ROOT/DISCOURSE_APPS"
