#!/usr/bin/env bash
source "$PLUGIN_AVAILABLE_PATH/discourse/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

discourse-create-cmd() {
  # shellcheck disable=SC2034
  declare desc="creates a discourse app"
  shift
  discourse_create_app "$@"
}

discourse-create-cmd "$@"
