#!/usr/bin/env bash
source "$PLUGIN_AVAILABLE_PATH/discourse/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

discourse-destroy-cmd() {
  declare desc="destroys a discourse app"
  shift
  discourse_destroy_app "$@"
}

discourse-destroy-cmd "$@"
