#!/usr/bin/env bash
source "$PLUGIN_AVAILABLE_PATH/discourse/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

discourse-install-plugin-cmd() {
  # shellcheck disable=SC2034
  declare desc="installs a discourse plugin"
  shift
  discourse_install_plugin "$@"
}

discourse-install-plugin-cmd "$@"
