#!/usr/bin/env bash
source "$PLUGIN_AVAILABLE_PATH/discourse/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

discourse-list-cmd() {
  declare desc="lists all discourse apps"
  discourse_list
}

discourse-list-cmd "$@"
