#!/usr/bin/env bash
source "$PLUGIN_AVAILABLE_PATH/discourse/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

discourse-restore-cmd() {
  declare desc="restores a discourse app"
  shift
  discourse_restore_app "$@"
}

discourse-restore-cmd "$@"
